apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sematextagents.sematext.com
spec:
  group: sematext.com
  names:
    kind: SematextAgent
    listKind: SematextAgentList
    plural: sematextagents
    singular: sematextagent
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: Your account data
              type: object
              properties:
                infraToken:
                  description: The Infra App token from your SC account
                  type: string
                region:
                  description: The region where your account data is hosted. Can be EU or US
                  type: string
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sematext-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sematext-operator
subjects:
- kind: ServiceAccount
  name: sematext-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sematext-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sematext-operator
  template:
    metadata:
      labels:
        name: sematext-operator
    spec:
      serviceAccountName: sematext-operator
      containers:
        - name: sematext-operator
          image: docker.io/sematext/sematext-operator:1.0.46
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sematext-operator"
