agent:
  image:
    repository: sematext/agent
    tag: latest
    pullPolicy: Always
  service:
    port: 80
    type: ClusterIP
  config:
    PIPELINE_CONSOLE_OUTPUT: false
    PIPELINE_NULL_OUTPUT: false
    API_SERVER_HOST: 0.0.0.0
    LOGGING_WRITE_EVENTS: false
    LOGGING_REQUEST_TRACKING: false
    AUTODISCO_ALLOWED_NAMESPACES: "default"
    LOGGING_LEVEL: info
  resources: {}

logagent:
  image:
    repository: sematext/logagent
    tag: latest
    pullPolicy: Always
  
  # Refer to Logagent docs for adding env vars to the config at 
  # https://sematext.com/docs/logagent/installation-docker/#configuration-parameters
  # Any Logagent env var can be added here in the `config`.
  config:
    LOGSENE_BULK_SIZE: "1000"
    LOGSENE_LOG_INTERVAL: "10000"
    # LOG_GLOB: "/var/log/*" # if you are using the Containerd container runtime in Kubernetes, set this value. Otherwise ignore it.
    # IGNORE_LOGS_PATTERN: "healthcheck|ping" # Drops logs with a regular expression.
    # MATCH_BY_NAME: ".*nginx.*" # Regular expression to include sending logs from these container names.
    # MATCH_BY_IMAGE: ".*nginx.*" # Regular expression to include sending logs from these image names.
    # SKIP_BY_NAME: ".*nginx.*" # Regular expression to exclude sending logs from these container names.
    # SKIP_BY_IMAGE: ".*nginx.*" # Regular expression to exclude sending logs from these image names.
    # REMOVE_FIELDS: "password,creditCardNo" # Removes fields from parsed/enriched logs.

  # Refer to logagent docs for custom config at https://sematext.com/docs/logagent/config-file/
  customConfigs: []
    # logagent.conf: |-
    #     options:
    #       printStats: 60
    #       suppress: true
    #       geoipEnabled: true
    #       diskBufferDir: /tmp/sematext-logagent
    #     parser:
    #       patternFiles:
    #         - /etc/logagent/patterns.yml
    #     output:
    #       logsene:
    #         module: elasticsearch
    #         url: ${LOGSENE_RECEIVER_URL}

  resources: {}
  extraHostVolumeMounts: {}
  #  - name: <mountName>
  #    hostPath: <hostPath>
  #    mountPath: <mountPath>

priorityClassName:

rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

# represents the infra token where most metrics, packages, processes, etc. are shipped
infraToken: null
# determines the token for the container app (container metrics are delivered here)
containerToken: null
# logs token to send logs
logsToken: null

# for private images
# imagePullSecrets:

region: US

# support for custom URLs
serverBaseUrl: null
eventsReceiverUrl: null
logsReceiverUrl: null
commandServerUrl: null

tolerations: []

# Node labels for pod assignment
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}
