apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sematextagents.sematext.com
spec:
  group: sematext.com
  names:
    kind: SematextAgent
    listKind: SematextAgentList
    plural: sematextagents
    singular: sematextagent
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties: {}
    subresources:
      status: { }
