apiVersion: apps/v1
kind: Deployment
metadata:
  name: sematext-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sematext-operator
  template:
    metadata:
      labels:
        name: sematext-operator
    spec:
      serviceAccountName: sematext-operator
      containers:
        - name: sematext-operator
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sematext-operator"
